### ISSUE TITLE
Add Error Handling for API Failure in script.js

### ISSUE THREAD

**Issue by Sagar2006** [iRupam/RandomJoke#4]
## Description:

Currently, the RandomJoke application doesn't provide feedback to the user when an error occurs during the joke fetch operation. If the API request fails (e.g., due to network issues or API downtime), the app should display a message to the user.

## Proposed Solution:

Update the fetchDataAndUpdateUI function in script.js to handle errors and show a user-friendly message when the API call fails.

## Steps:

Add a .catch block to the existing fetch function to handle errors.
Display a message like "Oops! Couldn't fetch a joke right now." in the #output div when the fetch request fails.

**Comment by Sagar2006** [comment]
kindly assign this issue to me!!!!

**Comment by iRupam** [comment]
@Sagar2006 Please go ahead.

**Comment by Sagar2006** [comment]
kindly check the pull request #6 Error Handling UPDATE
